// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: com/yangzone/protocol/link.proto

package protocol

import (
	context "context"
	link "github.com/yangzone/core/link"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkClient is the client API for Link service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkClient interface {
	// 创建
	Add(ctx context.Context, in *link.AddReq, opts ...grpc.CallOption) (*link.AddRsp, error)
	// 获取
	Get(ctx context.Context, in *link.GetReq, opts ...grpc.CallOption) (*link.GetRsp, error)
	// 分页
	Paging(ctx context.Context, in *link.PagingReq, opts ...grpc.CallOption) (*link.PagingRsp, error)
	// 修改
	Update(ctx context.Context, in *link.UpdateReq, opts ...grpc.CallOption) (*link.UpdateRsp, error)
	// 删除
	Delete(ctx context.Context, in *link.DeleteReq, opts ...grpc.CallOption) (*link.DeleteRsp, error)
}

type linkClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkClient(cc grpc.ClientConnInterface) LinkClient {
	return &linkClient{cc}
}

func (c *linkClient) Add(ctx context.Context, in *link.AddReq, opts ...grpc.CallOption) (*link.AddRsp, error) {
	out := new(link.AddRsp)
	err := c.cc.Invoke(ctx, "/com.yangzone.protocol.Link/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Get(ctx context.Context, in *link.GetReq, opts ...grpc.CallOption) (*link.GetRsp, error) {
	out := new(link.GetRsp)
	err := c.cc.Invoke(ctx, "/com.yangzone.protocol.Link/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Paging(ctx context.Context, in *link.PagingReq, opts ...grpc.CallOption) (*link.PagingRsp, error) {
	out := new(link.PagingRsp)
	err := c.cc.Invoke(ctx, "/com.yangzone.protocol.Link/Paging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Update(ctx context.Context, in *link.UpdateReq, opts ...grpc.CallOption) (*link.UpdateRsp, error) {
	out := new(link.UpdateRsp)
	err := c.cc.Invoke(ctx, "/com.yangzone.protocol.Link/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkClient) Delete(ctx context.Context, in *link.DeleteReq, opts ...grpc.CallOption) (*link.DeleteRsp, error) {
	out := new(link.DeleteRsp)
	err := c.cc.Invoke(ctx, "/com.yangzone.protocol.Link/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkServer is the server API for Link service.
// All implementations must embed UnimplementedLinkServer
// for forward compatibility
type LinkServer interface {
	// 创建
	Add(context.Context, *link.AddReq) (*link.AddRsp, error)
	// 获取
	Get(context.Context, *link.GetReq) (*link.GetRsp, error)
	// 分页
	Paging(context.Context, *link.PagingReq) (*link.PagingRsp, error)
	// 修改
	Update(context.Context, *link.UpdateReq) (*link.UpdateRsp, error)
	// 删除
	Delete(context.Context, *link.DeleteReq) (*link.DeleteRsp, error)
	mustEmbedUnimplementedLinkServer()
}

// UnimplementedLinkServer must be embedded to have forward compatible implementations.
type UnimplementedLinkServer struct {
}

func (UnimplementedLinkServer) Add(context.Context, *link.AddReq) (*link.AddRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedLinkServer) Get(context.Context, *link.GetReq) (*link.GetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLinkServer) Paging(context.Context, *link.PagingReq) (*link.PagingRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Paging not implemented")
}
func (UnimplementedLinkServer) Update(context.Context, *link.UpdateReq) (*link.UpdateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedLinkServer) Delete(context.Context, *link.DeleteReq) (*link.DeleteRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLinkServer) mustEmbedUnimplementedLinkServer() {}

// UnsafeLinkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkServer will
// result in compilation errors.
type UnsafeLinkServer interface {
	mustEmbedUnimplementedLinkServer()
}

func RegisterLinkServer(s grpc.ServiceRegistrar, srv LinkServer) {
	s.RegisterService(&Link_ServiceDesc, srv)
}

func _Link_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(link.AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yangzone.protocol.Link/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Add(ctx, req.(*link.AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(link.GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yangzone.protocol.Link/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Get(ctx, req.(*link.GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Paging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(link.PagingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Paging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yangzone.protocol.Link/Paging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Paging(ctx, req.(*link.PagingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(link.UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yangzone.protocol.Link/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Update(ctx, req.(*link.UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Link_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(link.DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yangzone.protocol.Link/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkServer).Delete(ctx, req.(*link.DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Link_ServiceDesc is the grpc.ServiceDesc for Link service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Link_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.yangzone.protocol.Link",
	HandlerType: (*LinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Link_Add_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Link_Get_Handler,
		},
		{
			MethodName: "Paging",
			Handler:    _Link_Paging_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Link_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Link_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/yangzone/protocol/link.proto",
}
